---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, eval=T, message = F, warning=F)
```

```{r}
library(dplyr)
library(ntpu)
```


## Read XLSX

```{r}
library(readxl)
sheet_aggregate <- read_excel("~/Downloads/1100319個人申請模擬書審成績試算-6位委員.xlsx",
                              col_types = c("numeric", "text", "numeric",
                                            "numeric", "numeric", "numeric",
                                            "numeric", "numeric", "numeric",
                                            "numeric"), skip = 2)
sheet_detail <- read_excel("~/Downloads/1100319個人申請模擬書審成績試算-6位委員.xlsx",
sheet = "一般組各面向成績", col_types = c("text",
"numeric", "text", "numeric", "numeric",
"numeric", "numeric", "numeric",
"numeric"), skip = 2)

# code start --------------------------------------------------------------
names(sheet_aggregate) %>%
  {which(stringr::str_length(.)==1)} -> whichIsCommittees
committeeNames <- names(sheet_aggregate)[whichIsCommittees]
```

## Analysis

```{r}
analysis <- ntpu:::Analysis()

analysis$sheets$append_sheet(sheet_aggregate, "aggregate")
analysis$sheets$append_sheet(sheet_detail, "detail")

# long table of aggregate grades
tbLong_grades <- {
  tidyr::pivot_longer(
    analysis$sheets$aggregate,
    cols = analysis$info$committeeNames,
    names_to = "committee",
    values_to = "grade"
  )
}

analysis$sheets$append_sheet(tbLong_grades, "aggregate_long")


colnames4standardise = analysis$columns2standardise_template()
colnames4standardise$colname_ID = "學測應試號碼"
colnames4standardise$colname_committee = "委員"
colnames4standardise$colname_aspects = stringr::str_subset(
  names(analysis$sheets$detail), "^[ABCD]")
colnames4standardise$colname_total = "總分(A*35%+B*15%+C*20%+D*30)"

sheet_name = "detail"

analysis$standardise_sheet(sheet_name = sheet_name, colnames4standardise = colnames4standardise)

analysis$sheets$standardised_detail %>% View()

```

## disparity

```{r}
df_all <- analysis$sheets$standardised_detail

assessList <- list()
df_all %>%
  mutate(
    評分老師 = as.factor(評分老師),
    ID = as.factor(ID)
  ) -> df_all

prepare_rankDF_byColumnX <- function(df_all, columnX){
  columnX_quo <- rlang::enquo(columnX)
  # browser()
  df_all %>%
    group_by(ID) %>%
    summarise(
      averageAll=mean(!!columnX_quo) # mean(total),
    ) %>%
    mutate(
      rankAll=rank(averageAll)
    ) 

}

prepare_rankDF_byColumnX(df_all, total) -> assessList$df_all

library(rlang)
levels(df_all$評分老師)-> listEvalutators
for(i in seq_along(listEvalutators)){
  df_name <- paste0("df_exclude_",i)
  df_exclude <- df_all %>%
    filter(
      評分老師!=listEvalutators[[i]]
    ) %>%
    group_by(ID) %>%
    summarise(
      average=mean(total),
    ) %>%
    mutate(
      rank=rank(average),
      exclude=listEvalutators[[i]]
    ) 
  assign(df_name,df_exclude) 
}
bind_rows(
  df_exclude_1,df_exclude_2,df_exclude_3,
  df_exclude_4,df_exclude_5,df_exclude_6
) %>%
  mutate(
    exclude=as.factor(exclude)
  )-> assessList$df_exclude
```

```{r}
# 將學生名字依名次排序
assessList$df_all$ID -> allNames
assessList$df_all$rankAll -> rankAll
allNames[rankAll] <- allNames 

# df_exclude
# assessList$df_exclude

# 排除委員自己後的比序
assessList$df_exclude %>%
  select(-average) %>%
  tidyr::pivot_wider(
    names_from = "ID", values_from = "rank"
  ) -> df_exclude_spread

# df_exclude_spread[,c("exclude",as.character(allNames))]

df_all %>%
  group_by(評分老師) %>%
  mutate(
    rank_self=as.integer(rank(total))
  ) %>%
  ungroup() %>%
  select(
    ID, 評分老師, rank_self
  ) %>%
  rename(
    "name_self"="ID"
    )-> df_rankSelf

assessList$df_exclude  %>%
  rename(
    "rank_exclude"="rank",
    "student"="ID"
  ) %>%
  select(
    exclude, rank_exclude, student
  ) %>%
  left_join(
    df_rankSelf,
    by=c("exclude"="評分老師", "student"="name_self")
  ) -> df_rankComparison #%>% View("rankExam")

# df_rankComparison # rank_self: 1委員排序  rank_exclude: 排1委員排序

df_rankComparison %>%
  left_join(
    assessList$df_all %>%
      select(ID,rankAll),
    by=c("student"="ID")
  ) %>%
  rename(
    "排序:排除一位委員"="rank_exclude",
    "排序:單一委員"="rank_self",
    "排序:全部委員"="rankAll",
    "委員"="exclude"
  ) -> df_final
```

## Graph：全部（含原住民）

### 單一委員左右排序

```{r}
library(ggplot2)
ggplot(data=df_final) +
  geom_abline(
    slope=1, intercept=0, size=1, alpha=0.3
  ) +
  geom_line(
    aes(
      x=`排序:全部委員`, y=`排序:排除一位委員`,
      group=委員,
      color=委員
    )
  ) +
  scale_x_continuous(
    breaks = 1:10
  )-> gg_disparity1
  
plotly::ggplotly(gg_disparity1)
```

<!--
### 委員偏好與其他人差異

```{r}
library(ggplot2)
ggplot(data=df_final) +
  geom_abline(
    slope=1, intercept=0, size=1, alpha=0.3
  ) +
  geom_line(
    aes(
      x=`排序:單一委員`, y=`排序:排除一位委員`,
      group=委員,
      color=委員
    )
  ) +
  scale_x_continuous(
    breaks = 1:10
  )-> gg_disparity2
  
plotly::ggplotly(gg_disparity2)
```





-->


## Table: 

```{r}
analysis$sheets$standardised_detail %>%
  tidyr::pivot_longer(
    cols = A:D,
    names_to = "面向",
    values_to = "分數"
  ) -> analysis$sheets$wide_rangeTable
```

### A

```{r}
aspect = "A"
ntpu:::get_aspectTable(analysis$sheets$wide_rangeTable, aspect)
```

### B

```{r}
ntpu:::get_aspectTable(analysis$sheets$wide_rangeTable, "B")

```

### C

```{r}
ntpu:::get_aspectTable(analysis$sheets$wide_rangeTable, "C")

```

### C

```{r}
ntpu:::get_aspectTable(analysis$sheets$wide_rangeTable, "D") 

```



